### PR TITLE
Some fixes

### PR DESCRIPTION
**Pull request by AkariDN**
Fixes:
* Fix exception when title description or credits text contains html tags like br
* Fix exception when no additional information supplied in title description
* Fix episode listing: some seasons were empty like [this title](https://www.wakanim.tv/ru/v2/catalogue/show/329/eksklyuzivnoe-intervyu-yevgenii-medvedevoy)

Also I've added last aired episodes list in separate [branch](https://github.com/AkariDN/plugin.video.wakanim/commits/lastep), please look if you find it useful...

### CODE REVIEW

**Comment by AkariDN** [comment]
Wait please, some rework on commits needed

**Comment by MrKrabat** [comment]
Thanks for fixing this :)

last aired episodes looks good 👍

**Comment by AkariDN** [comment]
Create pull request for last aired episodes?

**Comment by MrKrabat** [comment]
Yes, you can

**Pull request merged**
