### PR TITLE
Python3 support

### PR DESCRIPTION
**Pull request by AkariDN**
Python3 support:
- [x] Merge my branch 'master' with 'MrKrabat/python3'
- [x] Make it work on python2
- [x] Fix MrKrabat's remarks
- [x] Common testing on Kodi+python2
- [x] Make it work on python3
- [x] Common testing on Kodi+python3
- [x] Improve code quality

P.S. Kodi+python3 has a lot of bugs itself, e.g. CPythonInvoker cannot start plugin if it's located at path with unicode characters. Did we hurry up with python3 support?

P.P.S. Video playback tested only with HLS streams. I can't test DRM on Windows because InputStream Adaptive works only on android for now (or I'm wrong and it can be started  on WIndows or Linux?)

### CODE REVIEW

**Comment by AkariDN** [comment]
So far, that's it. Suspending futher work until merged.

**Comment by MrKrabat** [comment]
The problem with CPythonInvoker is currently not listed as known,
you may want to make a report https://forum.kodi.tv/showthread.php?tid=327928

Inputstream Adaptive with Widevine DRM works on:
- Windows (except Windows Store UWP App) with Kodi 17
- Mac OS X/iOS with Kodi 17
- Linux (incl. ARM devices) with Kodi 17
- Android with Kodi 18

Additionally it works on 32bit and 64bit OS/Kodi and with both Python versions.
Only inputstreamhelper does not support Python 3 currently.

**Comment by AkariDN** [comment]
Ready.

I have error on both windows and linux:
ERROR: AddOnLog: InputStream Adaptive: Unable to load widevine shared library (...\AppData\Roaming\Kodi\cdm\widevinecdm.dll)
Widevine CDM library is installed properly (manually from Chrome or with InputStreamHelper)

**Comment by AkariDN** [comment]
Finally tested DRM on Windows python2 and python3.

Is it so hard to handle unicode symbols in special://home? Path substitution special://home/cdm doesn't work too. Works only Kodi portable mode. Nevermind, it's all InputStream Adaptive issues..

**Pull request merged**
