### PR TITLE
Fix for 403 error when tryin to play video with "dash" protocol

### PR DESCRIPTION
**Pull request by ex0hunt**
Fix video url for dash proto (#21)

### CODE REVIEW

**Comment by Acreen** [comment]
After using your version of the plugin I was able to open series folders again. I was able to enter the catalogue but when tried to open a series there was a failure which is gone now! I hope it will be in the Kodirepo soon!

**Comment by ex0hunt** [comment]
Hi, @Acreen , thanks for feedback) On next time, if you catch this failure again, please send me last log (from ~/.kodi/temp/kodi.log). I'll tryin to understand whats happening :wink:

**Comment by Acreen** [comment]
[kodi.log](https://github.com/MrKrabat/plugin.video.wakanim/files/3903012/kodi.log)

**Comment by MrKrabat** [comment]
Thanks for helping out @ex0hunt :)

It looks like Wakanim changed a couple of things again, I will look what needs to be fixed

**Comment by MrKrabat** [comment]
@Acreen please try out the lastest version (manually install it from github).
If all works fine, I will update the Kodi repository :)

**Comment by Acreen** [comment]
The new version is working without errors again.

Just wondering if you have any clue why this plugin seems to have slight video decoding issues which the crunchyroll plugin doesnt. If I don't enforce 1080p several times a minute there are pixel erros in the picture. Even at 1080p it happens sometimes but maybe once every few minutes. As far as I understand crunchyroll, wakanim and aod all rely on the inputstream adaptive plugin so I don't get why there is a difference at all after the stream started.

**Comment by MrKrabat** [comment]
Crunchyroll and AOD are using standard HLS stream with AES encryption while Wakanim uses MPEG-DASH with Widevine DRM.
Maybe your device is just too weak to handle encryption and decoding with Widevine.

You could try to update Inputstream.adaptive (the easiest way is to use the latest Kodi version). Widevine should already be the latest version.

BUT maybe inputstream.adaptive is just stupid and switches the resolution without any reason, you can control this behaviour in the settings.

**Comment by Acreen** [comment]
I'm using kodi 18.5 on a PI 4b. It already offered an self update a few days ago which didn't change this. I already fixed the resolution which made it way better but the quality is still pending sometimes. Not even Netflix is behaving that way.

But thanks for the info with the difference between the services!

**Pull request merged**
